/**
 * ============================================================================
 * lung-model.js — Single-Compartment Linear RC Lung Model
 * ============================================================================
 *
 * THE EQUATION OF MOTION FOR THE RESPIRATORY SYSTEM
 *
 *   Pmus + Pvent = E × V + R × V̇
 *
 * Where:
 *   Pmus  = pressure generated by respiratory muscles (cmH2O)
 *   Pvent = pressure generated by ventilator (cmH2O), above PEEP
 *   E     = elastance of respiratory system (cmH2O/L) = 1/C
 *   V     = volume above end-expiratory equilibrium (L)
 *   R     = resistance of airways + ETT (cmH2O·s/L)
 *   V̇     = flow (L/s)
 *
 * The term E × V is the ELASTIC LOAD (PE) — force to expand lungs/chest wall.
 * The term R × V̇ is the RESISTIVE LOAD (PR) — force to drive flow through airways.
 *
 * This model treats the respiratory system as a single rigid tube (resistance)
 * connected to a single elastic compartment (compliance), with linear
 * (constant) R and C. Inertance is ignored as it is negligible at normal
 * breathing frequencies.
 *
 * REFERENCES:
 *   Chatburn RL. Fundamentals of Mechanical Ventilation. Mandu Press, 2003.
 *   Mireles-Cabodevila E, Siuba MT, Chatburn RL. Respir Care 2022;67(1):129–148.
 *   Arnal J-M, Garnero A, Saoli M, Chatburn RL. Respir Care 2018;63(2):158–168.
 *
 * UNITS CONVENTION (used throughout the entire simulator):
 *   Pressure:   cmH2O
 *   Volume:     L       (display in mL where noted)
 *   Flow:       L/s     (display in L/min where noted)
 *   Compliance: L/cmH2O (e.g., 0.05 L/cmH2O = 50 mL/cmH2O)
 *   Resistance: cmH2O·s/L (often written cmH2O/L/s)
 *   Time:       seconds
 *
 * ============================================================================
 */

export class LungModel {

    /**
     * Create a lung model with given mechanics.
     *
     * @param {Object} params
     * @param {number} params.resistance  - Total airway + ETT resistance (cmH2O·s/L)
     * @param {number} params.compliance  - Total respiratory system compliance (L/cmH2O)
     */
    constructor(params = {}) {
        this.resistance  = params.resistance  ?? 10;    // cmH2O·s/L
        this.compliance  = params.compliance  ?? 0.05;  // L/cmH2O

        // Pmus = 0 for passive patient (Milestone 0).
        // This will become a time-varying function in later milestones
        // to model patient effort, triggering, and asynchrony.
        this.pMus = 0;
    }


    // =========================================================================
    // DERIVED PROPERTIES
    // =========================================================================

    /**
     * Elastance E = 1/C (cmH2O/L)
     *
     * "When we say high elastance, it means low compliance and vice versa."
     *   — Mireles-Cabodevila et al. (2022), p. 132
     */
    get elastance() {
        return 1 / this.compliance;
    }

    /**
     * Time constant τ = R × C (seconds)
     *
     * "One time constant is the period of time where there is a 63% change
     *  in flow or volume (and hence alveolar pressure) in response to a step
     *  change in pressure at the airway opening."
     *   — Mireles-Cabodevila et al. (2022), p. 134
     *
     * Clinical rules of thumb:
     *   1τ → 63% change
     *   2τ → 87% change
     *   3τ → 95% change (minimum acceptable Te)
     *   5τ → 99.3% change (considered complete)
     *
     * The time constant returned here is calculated from this model's configured R and C.
     * Clinical expiratory time constants and published simulation recommendations are
     * different evidence types; do not substitute either for this calculation.
     */
    get timeConstant() {
        return this.resistance * this.compliance;
    }


    // =========================================================================
    // INSPIRATORY PHASE (Volume Control, Square Flow)
    // =========================================================================
    //
    // In VC with set-point targeting and a square (constant) flow waveform:
    //   - The ventilator controls flow (V̇ = constant = VT / Ti)
    //   - Volume ramps linearly: V(t) = V̇ × t
    //   - Pressure is the DEPENDENT variable that reveals the load
    //
    // "In VC you see the load and patient interactions in the pressure
    //  waveform. Ventilators are excellent at controlling flow, so the
    //  tidal volume and flow waveform will not change in the presence
    //  of Pmus for VC with set-point targeting."
    //   — Mireles-Cabodevila et al. (2022), p. 132
    //
    // Pressure waveform anatomy for VC square flow, passive patient:
    //
    //   P(t) = PEEP + autoPEEP + R × V̇ + V(t)/C
    //          ├─── baseline ──┤  ├─ PR ─┤  ├ PE(t)┤
    //
    //   At t = 0:   P = PEEP + autoPEEP + R × V̇         ← resistive step-up
    //   During Ti:  P rises linearly (because V rises linearly and V̇ is constant)
    //   At t = Ti:  P = PIP = PEEP + autoPEEP + R × V̇ + VT/C
    //   Hold:       P drops to Pplat = PEEP + autoPEEP + VT/C  (R × 0 = 0)
    //
    // The slope of the pressure rise during inspiration = V̇/C = V̇ × E
    //   Steep slope → high elastance (stiff lungs, e.g., ARDS)
    //   Gentle slope → low elastance (compliant lungs)
    //
    // =========================================================================

    /**
     * Airway pressure during VC inspiration at a given moment.
     *
     * @param {number} volume   - Volume delivered so far this breath (L)
     * @param {number} flow     - Current inspiratory flow (L/s), positive
     * @param {number} peep     - Set PEEP (cmH2O)
     * @param {number} autoPeep - Steady-state auto-PEEP (cmH2O)
     * @returns {number} Airway pressure (cmH2O)
     */
    inspiratoryPressure(volume, flow, peep, autoPeep = 0) {
        const resistiveLoad = this.resistance * flow;     // PR = R × V̇
        const elasticLoad   = volume / this.compliance;   // PE = V / C = E × V
        return peep + autoPeep + resistiveLoad + elasticLoad;
    }

    /**
     * Plateau pressure (during inspiratory hold, flow = 0).
     *
     * "If the flow stops (manual or preset inspiratory hold), the resistive
     *  load is zero (R × 0 = 0) and only the elastic load remains."
     *   — Mireles-Cabodevila et al. (2022), p. 133
     *
     * @param {number} volume   - Volume in lung above equilibrium (L)
     * @param {number} peep     - Set PEEP (cmH2O)
     * @param {number} autoPeep - Auto-PEEP (cmH2O)
     * @returns {number} Plateau pressure (cmH2O)
     */
    plateauPressure(volume, peep, autoPeep = 0) {
        return peep + autoPeep + (volume / this.compliance);
    }


    // =========================================================================
    // EXPIRATORY PHASE (Passive — applies to both VC and PC)
    // =========================================================================
    //
    // "The expiratory phase is normally passive due to the recoil of the lungs
    //  and chest wall. The expiratory phase in mechanical ventilation is ALWAYS
    //  pressure controlled. That is, during expiration the ventilator controls
    //  the pressure (ie, you set the PEEP)."
    //   — Mireles-Cabodevila et al. (2022), p. 136
    //
    // After a step change in pressure from Pplat to PEEP:
    //
    //   V̇(t)  = -(ΔP / R) × e^(-t/τ)        Exponential decay of flow
    //   V(t)  = V_start × e^(-t/τ)            Volume remaining above equilibrium
    //   P(t)  = PEEP + (V_start / C) × e^(-t/τ)  Alveolar pressure decay
    //
    // where:
    //   ΔP = V_start / C = total elastic recoil pressure at start of expiration
    //   V_start = total volume above PEEP equilibrium (includes trapped gas)
    //   τ = R × C
    //
    // =========================================================================

    /**
     * Expiratory flow at time t into expiration.
     * Returns a negative value (expiratory flow convention).
     *
     * @param {number} volumeStart      - Volume above equilibrium at start of expiration (L)
     * @param {number} timeIntoExp      - Time since start of expiration (s)
     * @returns {number} Flow (L/s), negative
     */
    expiratoryFlow(volumeStart, timeIntoExp) {
        const tau = this.timeConstant;
        const deltaP = volumeStart / this.compliance;
        return -(deltaP / this.resistance) * Math.exp(-timeIntoExp / tau);
    }

    /**
     * Volume remaining above PEEP equilibrium during passive expiration.
     *
     * @param {number} volumeStart  - Volume above equilibrium at start of expiration (L)
     * @param {number} timeIntoExp  - Time since start of expiration (s)
     * @returns {number} Volume remaining (L)
     */
    expiratoryVolumeRemaining(volumeStart, timeIntoExp) {
        return volumeStart * Math.exp(-timeIntoExp / this.timeConstant);
    }

    /**
     * Airway pressure during passive expiration.
     *
     * @param {number} volumeStart  - Volume above equilibrium at start of expiration (L)
     * @param {number} timeIntoExp  - Time since start of expiration (s)
     * @param {number} peep         - Set PEEP (cmH2O)
     * @returns {number} Airway pressure (cmH2O)
     */
    expiratoryPressure(volumeStart, timeIntoExp, peep) {
        const vRemaining = this.expiratoryVolumeRemaining(volumeStart, timeIntoExp);
        return peep + (vRemaining / this.compliance);
    }


    // =========================================================================
    // AUTO-PEEP AND GAS TRAPPING
    // =========================================================================
    //
    // "Dynamic hyperinflation is the process by which lung volume increases
    //  whenever insufficient exhalation time prevents the respiratory system
    //  from returning to its resting end-expiratory equilibrium volume."
    //   — Chatburn, Fundamentals of Mechanical Ventilation, Ch. 3
    //
    // "autoPEEP is defined as the positive difference between end-expiratory
    //  alveolar pressure and the end-expiratory airway pressure (PEEP)
    //  selected by the clinician."
    //   — Chatburn, ibid.
    //
    // In steady state, what goes in must come out each breath:
    //
    //   V_exhaled = (V_trapped + VT) × (1 - e^(-Te/τ)) = VT
    //
    // Solving for V_trapped:
    //
    //   V_trapped = VT × e^(-Te/τ) / (1 - e^(-Te/τ))
    //
    //   autoPEEP = V_trapped / C
    //
    // When Te ≥ 5τ, e^(-Te/τ) ≈ 0, so V_trapped ≈ 0 and autoPEEP ≈ 0.
    // When Te < 3τ, auto-PEEP becomes clinically significant.
    //
    // =========================================================================

    /**
     * Steady-state trapped gas volume (L).
     *
     * @param {number} tidalVolume    - Tidal volume per breath (L)
     * @param {number} expiratoryTime - Available expiratory time (s)
     * @returns {number} Trapped volume (L)
     */
    steadyStateTrappedVolume(tidalVolume, expiratoryTime) {
        const tau = this.timeConstant;
        const expFactor = Math.exp(-expiratoryTime / tau);

        // Guard: if exp factor is essentially 1, no exhalation occurs
        if (expFactor >= 0.999) return Infinity;

        return tidalVolume * expFactor / (1 - expFactor);
    }

    /**
     * Steady-state auto-PEEP (cmH2O).
     *
     * @param {number} tidalVolume    - Tidal volume per breath (L)
     * @param {number} expiratoryTime - Available expiratory time (s)
     * @returns {number} Auto-PEEP (cmH2O)
     */
    steadyStateAutoPeep(tidalVolume, expiratoryTime) {
        const trappedVolume = this.steadyStateTrappedVolume(tidalVolume, expiratoryTime);
        if (!isFinite(trappedVolume)) return Infinity;
        return trappedVolume / this.compliance;
    }


    // =========================================================================
    // PATIENT PRESETS
    // =========================================================================
    //
    // Mechanics examples for the linear single-compartment model.
    // R combines airway and tube resistance; C is total respiratory-system compliance.
    // The model does not partition chest wall from lung or simulate a humidifier separately.
    // The COPD example uses the R/C pair in Arnal et al., Respir Care 2018;63(2):158-168,
    // doi:10.4187/respcare.05775, Table 9, COPD with HME.
    // The other pairs are retained project examples, not source-prescribed disease values.
    // All preset time constants are calculated as R*C with C in L/cmH2O.
    // See docs/clinical/CLIN-009/preset-provenance.md for the approved per-preset decisions.
    //
    // =========================================================================

    /**
     * Returns a dictionary of mechanics examples with configured resistance,
     * compliance, a label, and an explanatory note.
     *
     * @returns {Object} Preset dictionary
     */
    static presets() {
        return {
            normal: {
                resistance:  10,
                compliance:  0.060,
                label:       "Normal example",
                note:        "Illustrative starting values: R = 10 cmH₂O·s/L; C = 60 mL/cmH₂O. Calculated τ = 0.60 s. This pair is a project example, not Arnal's recommended Normal pair.",
            },
            ards_moderate: {
                resistance:  10,
                compliance:  0.035,
                label:       "Low compliance (35)",
                note:        "Illustrative starting values: R = 10 cmH₂O·s/L; C = 35 mL/cmH₂O. Calculated τ = 0.35 s. The name describes the configured compliance, not ARDS severity.",
            },
            ards_severe: {
                resistance:  12,
                compliance:  0.025,
                label:       "Low compliance (25)",
                note:        "Illustrative starting values: R = 12 cmH₂O·s/L; C = 25 mL/cmH₂O. Calculated τ = 0.30 s. The name describes the configured compliance, not ARDS severity.",
            },
            copd: {
                resistance:  25,
                compliance:  0.060,
                label:       "COPD example (HME)",
                note:        "Starting values: R = 25 cmH₂O·s/L; C = 60 mL/cmH₂O. Calculated τ = 1.50 s. This pair follows Arnal et al. (2018), Table 9, for a COPD simulation with a heat-and-moisture exchanger (HME). The study measured passive, intubated adults in one ICU and excluded BMI above 30 and mixed lung conditions. The model uses combined resistance; it does not simulate the HME separately.",
            },
            asthma: {
                resistance:  20,
                compliance:  0.060,
                label:       "High resistance (20)",
                note:        "Illustrative starting values: R = 20 cmH₂O·s/L; C = 60 mL/cmH₂O. Calculated τ = 1.20 s. This example explores increased resistance; it is not a validated acute-asthma preset.",
            },
            obesity: {
                resistance:  8,
                compliance:  0.040,
                label:       "Reduced compliance (40)",
                note:        "Illustrative starting values: R = 8 cmH₂O·s/L; C = 40 mL/cmH₂O. Calculated τ = 0.32 s. This example changes total respiratory-system compliance. It does not identify a chest-wall cause or represent validated obesity mechanics.",
            },
            fibrosis: {
                resistance:  8,
                compliance:  0.030,
                label:       "Low compliance (30)",
                note:        "Illustrative starting values: R = 8 cmH₂O·s/L; C = 30 mL/cmH₂O. Calculated τ = 0.24 s. This example explores reduced compliance; it is not a validated pulmonary-fibrosis preset.",
            },
        };
    }

    /**
     * Create a LungModel from a named preset.
     *
     * @param {string} presetName - Key from LungModel.presets()
     * @returns {LungModel}
     */
    static fromPreset(presetName) {
        const presets = LungModel.presets();
        const preset = presets[presetName];
        if (!preset) {
            throw new Error(
                `Unknown preset "${presetName}". ` +
                `Available: ${Object.keys(presets).join(', ')}`
            );
        }
        return new LungModel({
            resistance: preset.resistance,
            compliance: preset.compliance,
        });
    }
}
